Added destroy, update, read, and create routes for the Task entity
scrumzone/tasktree pull request #101
Opened 2022-10-22 18:26 UTC by zmalkmus

I think this is close, the only thing I am concerned about is with the task request files. But feel free to make sure that everything is correct because I am still very much learning what is going on with the backend lol.

2022-10-24 01:16 UTC, zaviermiller requested changes
good stuff, couple changes

2022-10-24 01:16 UTC, zaviermiller commented on backend/TaskTree/Controllers/TasksController.cs
> +        // POST: api/Tasks
this should be something like `/api/tasks/{parentId}/create` since we want tasks that are created through the api to have a parent task.

2022-10-24 01:16 UTC, zaviermiller commented on backend/TaskTree/Controllers/TasksController.cs
> +                tasks.Add(_mapper.Map<Task, TaskResponse>(task));
this needs to be defined in `MappingProfile.cs`

2022-10-24 01:16 UTC, zaviermiller commented on backend/TaskTree/Controllers/TasksController.cs
> +            return task;
need to return the mapping of task to task response

2022-10-24 01:16 UTC, zaviermiller commented on backend/TaskTree/Models/Requests/CreateTaskRequest.cs
> +namespace TaskTree.Models.Requests
this object represents the information passed into the controller when creating a task. when creating a task, there will only be a name, description, and weight passed in.

2022-10-24 01:16 UTC, zaviermiller commented on backend/TaskTree/Models/Requests/UpdateTaskRequest.cs
> +        public string? Name { get; set; } = null!;
same as above, when updating a project through the api, there will probably only be updates to name, description, weight and completed at.

2022-10-24 01:47 UTC, andlrutt requested changes

2022-10-24 01:47 UTC, andlrutt commented on backend/TaskTree/Controllers/TasksController.cs
> +namespace TaskTree.Controllers
Every authorized route (POST, PUT, and the GETs), should have the [Authorize] attribute above it, as well as the `CurrentUserIdDoesNotMatch()` check. for the GET Tasks endpoint, you'll probably have to get the project and then use the userId from that to call `CurrentUserIdDoesNotMatch`

2022-10-24 01:47 UTC, andlrutt commented on backend/TaskTree/Controllers/TasksController.cs
> +                else if (exceptionCode == -2146233088)
Ran the service locally, set a breakpoint in the `catch`, and looked at the returned object

2022-10-25 04:12 UTC, andlrutt approved these changes
Awesome!

2022-10-25 04:29 UTC, merged